# Generated by Django 2.2.2 on 2019-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'cloth_type',
            },
        ),
        migrations.CreateModel(
            name='fault_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_mark', models.CharField(max_length=20)),
                ('fault_mark', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'fault_num',
            },
        ),
        migrations.CreateModel(
            name='Fault_Tpye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'fault_type',
            },
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'picture',
            },
        ),
    ]
